### ISSUE TITLE
lsp

### ISSUE THREAD

**Issue by shautvast** [zed-extensions/java#4]
it would be nice to have an actual LSP right? I just finished it in the old style, something I had started a while back, before noticing that they added an extension mechanism and probably won't accept java as a standard language plugin.

https://github.com/shautvast/zed/tree/java_support

the code downloads a jvm and eclipse jdt, and starts it. Works nicely on my machine. Dunno how to integrate this into an extension, but you're free to use my code :)

**Comment by samuser107** [comment]
Hi thanks for that! For the moment, Zed doesn't integrate LSP but is planning to. So we have to sit tight for the time being before seeing that. When it's launched don't worry i'll be the first to try it and deploy it as soon as possible

**Comment by fdionisi** [comment]
I believe a new branch could be open already and start mimicking what has been done for [Gleam already](https://github.com/zed-industries/zed/tree/1dd4c1b057b1797a447a0494eacd65d9c0f0864c/extensions/gleam). 

An when [this DX PR](https://github.com/zed-industries/zed/pull/8781) land, it would be even easier. 😊

**Comment by shautvast** [comment]
aha, so there is a trait to implement for extensions. I had not seen that before

**Comment by 0x2CA** [comment]
Now has extensions to implement lsp
zed-industries/extensions/pull/356

**Comment by JosephTLyons** [comment]
> aha, so there is a trait to implement for extensions. I had not seen that before

Yeah, the trait didn't exist until recently. :)

**Comment by louisnicolas-longheval-vinci** [comment]
now that there is support for LSP, it would be great to add it. but in fact for the moment im kinda busy to add it and not very familiar with the whole process of adding it. If someone is familiar with it, you're welcome to fork the repo and create a PR that i will merge if it fits well.

**Comment by Braayy** [comment]
Any updates on this? I was trying to play a little with the extension API but i could get any meaningful result.

**Comment by quot** [comment]
> Any updates on this? I was trying to play a little with the extension API but i could get any meaningful result.

There is the "Java with Eclipse JDTLS" extension now. It can be installed through the Zed extensions page, and the repo for it can be found here: https://github.com/ABckh/zed-java-eclipse-jdtls

**Comment by valentinegb** [comment]
Hey, I originally worked on the other Java extension with LSP ^^

It seems like despite a superior extension existing, this objectively inferior extension is still more popular. So here's what I propose: having already implemented a Zed extension for Java with LSP before, I could create a PR for this extension doing the same thing again. Then, @ABckh could probably sunset the other Java extension in favor of this one. (I am acting alone in this proposal, so it's up to @ABckh whether they actually want to go along with this.)

This would be somewhat of a rewrite since this extension is quite old and is dissimilar to modern extensions with LSP support. I would expect to be allowed to add @ABckh and myself as authors considering, after the proposed PR is merged, this extension would be a consolidation of all our efforts.

Sorry for the little but of slander at the beginning ^^', I of course see how a more definitive sounding extension, just "Java", residing in the official Zed extension organization, is more appealing. This is the reason that I think I it's a good idea to consolidate- so that the more appealing extension is actually the better one, and everyone benefits.

How's all that sound? :)

**Comment by valentinegb** [comment]
Started working on it and progress is going pretty smoothly.

![Screenshot 2024-09-03 at 4 31 30 PM](https://github.com/user-attachments/assets/1330df61-f2bd-46c0-bc78-9e6501bb1109)

I'm pushing my changes as I make them to [a branch on my fork](https://github.com/valentinegb/zed-java/tree/lsp) if anybody wants to try it extra early ^^

**Comment by ABckh** [comment]
Hi @valentinegb,

I don't see the point of this, and it doesn't seem right to me that I was developing and maintaining the extension by myself, only for you to copy and paste the code from there into this repo. I would not like to lose ownership of the extension, but of course, I cannot stop you from using the initial `java-eclipse-jdtls` code.

**Comment by valentinegb** [comment]
@ABckh I'm a little offended you would assume I'm doing nothing more than copying from the other Java extension, and I'm more offended that you would completely discredit me for all the work I definitely remember doing on the extension that has my name on it and my commits in it.

In fact, I haven't referenced that extension whatsoever whilst developing the PR for this extension. I'm simply doing this going off the fact that *I already know how to since I did it before*.

Nobody said you were going to lose ownership of the extension.

The purpose is this to only to make things less confusing for Zed users and deliver a better experience.

**Comment by ABckh** [comment]
@valentinegb I did not mean discredit your work at all 🙂

Just for me it sounds unreasonable to support the same LSP server on 2 java extensions, as I would like to see tasks support and other improvements to the existing jdtls extension. It makes more sense for me to support different LSP server for this extension such as NetBeans, rather than sync 2 extensions to do mostly the same.

**Comment by 0x2CA** [comment]
> Hey, I originally worked on the other Java extension with LSP ^^
> 
> It seems like despite a superior extension existing, this objectively inferior extension is still more popular. So here's what I propose: having already implemented a Zed extension for Java with LSP before, I could create a PR for this extension doing the same thing again. Then, @ABckh could probably sunset the other Java extension in favor of this one. (I am acting alone in this proposal, so it's up to @ABckh whether they actually want to go along with this.)
> 
> This would be a tiny bit of a rewrite since this extension is a bit old and is now dissimilar to modern extensions with LSP support. I would expect to be allowed to add @ABckh and myself as authors considering, after the proposed PR is merged, this extension would be a consolidation of all our efforts.
> 
> Sorry for the little but of slander at the beginning ^^', I of course see how a more definitive sounding extension, just "Java", residing in the official Zed extension organization, is more appealing. This is the reason that I think I it's a good idea to consolidate- so that the more appealing extension is actually the better one, and everyone benefits.
> 
> How's all that sound? :)

This is not right, each extension should be equal, of course, you can't let him give up, the name issue you mentioned, can only be said that this repository simply preempted the name and then abandoned the update, what needs to be done now is to update this repository,  The main problem is that this repository has not been updated for a long time, and when @ABckh to take care of it, you want him to give up.Of course, his words might be a bit harsh, but in fact, his expansion has the possibility of being referenced, and of course, you might not have plagiarized his code.

I think the two extensions competing with each other is not a problem, users' eyes are sharp.

**Comment by valentinegb** [comment]
Okay, I'd like to apologize for seemingly forcing @ABckh into "giving up", that wasn't really my intention, or at least that's not how I had been looking at it o.o'

I don't have a problem with both extensions existing if @ABckh would like that, but *I* would like to work on this extension now (and why not, not like I'm carrying trade-secrets with me ¯\\\_(ツ)_/¯). I respect all involved with both extensions, and I don't think I should have an obligation to stick with developing for one.

@ABckh, I can assure you I won't be plagiarizing any of your work, I agree that's not quite fair to you. Still, I have seen code that you've produced before and indirectly learned from it, so that's why in my PR I've put your name in the list of authors. (I can remove it of course, if you would prefer not to be associated ^^)

And, more apologies, for my defensive response to you @ABckh, I may have misunderstood your intent.

**Comment by dlee13** [comment]
> now that there is support for LSP, it would be great to add it. but in fact for the moment im kinda busy to add it and not very familiar with the whole process of adding it. If someone is familiar with it, you're welcome to fork the repo and create a PR that i will merge if it fits well.

If @louisnicolas-longheval-vinci is not going to maintain this repo, this extension should get the sunset. And [java-eclipse-jdtls](https://github.com/ABckh/zed-java-eclipse-jdtls) doesn't need to move to the Zed extensions organization, but it should at least get to republish with the extension name as just "Java".
